bricolages/bricolage

- lib/bricolage/psqldatasource.rb
psql コマンドに追加のオプションを渡せるようにしたいです
example:
```ruby
psql_options = [
'--tuples-only',
'--output=/tmp/result'
]
execute(query, psql_options)
```
> Pass options to psql command

- lib/bricolage/context.rb
特定サブシステム内のジョブでだけ有効な変数ファイル SUBSYS/variable.yml を導入する。
config/**/variable.yml と同名の変数を定義した場合は SUBSYS 側が上書き。
> [NEW] Introduces subsystem-wise variable file SUBSYS/variable.yml

- lib/bricolage/job.rb
- lib/bricolage/parameters.rb
- lib/bricolage/variables.rb
- test/home/subsys/rebuild.sql.job
- test/home/subsys/variable.yml
グローバル変数 defaults に値をセットしておくことで、あらゆるジョブクラスのデフォルト値を設定できるようにする。
例: (SUBSYS/variable.yml)
```
defaults:
grant:
privilege: select
to: "group dwh_reader"
```
この設定をしておくことで、grantを持つ全ジョブがデフォルトでGRANTを発行するようになる。
なお、GRANTをしたくないジョブでは grant: false と書けばオフにできる。
grant以外でデフォルトをセットするとどうなるかは正直あんまり検討してない。
> [NEW] Introduces default job parameters (via "defaults" global variable)

- lib/bricolage/job.rb
- lib/bricolage/psqldatasource.rb
- lib/bricolage/vacuumlock.rb
- libexec/create-lockfile
- test/home/subsys/raw-vacuum.jobnet
VACUUM自体が失敗したときロックファイルが残ってしまっていたので、必ず消すようにした。
そもそもなんでロックファイルを消していなかったかというと、psql経由でSQLを実行しているので、ロックをかけたかどうかBricolage側でわからなかったのが問題。VACUUMが終わったあとに他のプロセスがロックしたかもしれないので、ファイルがあるからといって無条件に消すわけにはいかなかった。
そこでこのpullreqではロックファイルにBricolageのPIDを記録することで、自分がロックをかけたのか判別できるようにして問題を解決した。自分がロックをかけていたなら、自分で消さないかぎりロックはかかったままのはずであるから、間違って他人のロックを外してしまう危険はない。
この修正を加えたことで、クリーンナップが失敗するケースはRubyがSEGVなどで突然死した場合と、SIGKILLで殺された場合（つまりRubyレベルのensureが動作しない状況）に限定された。
> [FIX] Remove VACUUM lock when VACUUM failed

- lib/bricolage/jobfile.rb
- lib/bricolage/tddatasource.rb
TDジョブクラスでも.sql.jobをサポートする
ref: #19
> td-export: Supports .sql.job

- lib/bricolage/mysqldatasource.rb
以下の警告をつぶした
```
% ruby -wc lib/bricolage/mysqldatasource.rb
lib/bricolage/mysqldatasource.rb:69: warning: circular argument reference - sqldump
Syntax OK
```
> my-export, my-migrate: reduce syntax warning

- lib/bricolage/psqldatasource.rb
- lib/bricolage/s3datasource.rb
- test/home/subsys/load.job
暗号化されたS3オブジェクトをロードできるようにする。
ref: #42 
- s3 data sourceにmaster_symmetric_keyパラメーターを追加する
- master_symmetric_keyが設定されたs3 data sourceからロードする場合はcredential文字列にも自動的にmaster_symmetric_keyを追加する
- また同data sourceからロードするジョブではencryptedオプションが自動で有効になる（いちおう、encrypted: nullで明示的にオフにできる）
> Supports encrypted S3 data source

- lib/bricolage/psqldatasource.rb
encryptionオプションはclient-side encryption用なので不要
> [load, streaming_load] "encryption" option is not needed for SSE-KMS

- lib/bricolage/postgresconnection.rb
- lib/bricolage/redisdatasource.rb
- test/home/subsys/redis_export2.job
Problem: The redis-export jobclass exit with error when a key to set already exists in DB.
Solution: Remove error checking which is not working and needless.
Also include...
- Fix parameter name (typo)
- Improve error message
- Add test job
> [Fix] Redis export exit with error when a key to set already exists.

- jobclass/my-import.rb
- lib/bricolage/mysqldatasource.rb
- test/home/subsys/my-import.job
- test/home/subsys/users.ct
Add my-import jobclass which improve performance of data importing from mysql.
"my-import" dumps MySQL table directly to S3 without writing data on local storage.
Please note this jobclass requires decent amount of memory, a few GB, depends on number of writer concurrency.
**options**
`src-table`: source MySQL table name
`src-ds`: source MySQL data source
`sql-fil`e: MySQL query (optional)
`s3-ds`: S3 data source to store tmp data
`s3-prefix`: S3 prefix
`dump-options`: see below
`format`: json, tsv, csv. default: json
`partition_column`: column to partition source table (required to enable parallel read). no default.
`partition_number`: number of partitions = number of reader concurrency. default: 4
`writer_concurrency`: writer concurrency. default: 4
`rotation_size`: Preferred S3 Object …
> Add my-import jobclass

- jobclass/streaming_load.rb
streaming_loadジョブクラスでジョブ起動のたびに一時ログテーブル xxxx_l_tmpNNNN をdrop-createしていたのをやめて、常設の xxxx_l_wk を使うようにします。これにともない、streaming_loadでは xxxx_wk, xxxx_l, xxxx_l_wk の3つの補助テーブルが必須になります。
やめる理由は、drop, createなどのDDLが異常に遅くなる現象が発生しているため。これが原因かどうかはわかっていないものの、現在原因がまったくわからないのでとりあえずやってみる。
ただ、ワークテーブルが増えてきてさすがに面倒なので、現在開発中の streaming_load v3（独立ストリーミングローダー）で全テーブルまとめて処理できるようにする予定。
> [streaming_load][CHANGE] Reuse fixed temporary log table

- lib/bricolage/mysqldatasource.rb
ハッシュのキーが文字列であるにも関わらず、省略記法で書かれているため修正します
> Fix S3Export command parameter key specification in MySQLDataSource

- jobclass/streaming_load.rb
いくつかのRedshiftクラスターにおいて、COPYのanalyze compression phaseで以下のエラーが発生する謎のバグに出会ったので回避を試みる
```
-----------------------------------------------
error:  Assert
code:      1000
context:   (fieldstr - curr) < len - Error: (fieldstr - curr):0 is greater than len:0
query:     3805233
location:  tbl_trans.cpp:1171
process:   query1_57 [pid=57628]
-----------------------------------------------
```
> streaming_load: FIX?: disable compupdate

- Gemfile.lock
- bricolage.gemspec
This commit fixes an error like
```
LoadError: cannot load such file -- bricolage/jobclass
```
when kick 'rake test'
> Use rake with bundler

- .gitignore
- lib/bricolage/sqsdatasource.rb
- lib/bricolage/streamingload/dispatcher.rb
- lib/bricolage/streamingload/event.rb
- lib/bricolage/streamingload/loader.rb
- lib/bricolage/streamingload/loaderparams.rb
- lib/bricolage/streamingload/loaderservice.rb
- lib/bricolage/streamingload/objectbuffer.rb
- utils/init_strload_tables.sql
課題
テーブルごとに異なるトランザクションでタスクがインサートされているため、コミット回数が多い。コミットは待たされることが多いため、パフォーマンスが悪い。
対応
同じタイミングで実行されるタスクのインサートを1トランザクション化
課題
全テーブルが同じ間隔でロードされると、ロードが追いつかない場合がある
対応
テーブル毎にロード間隔を設定できるようにする
> 複数テーブルのタスクのロードを1トランザクションと、テーブル毎のロードインターバルのサポート

- jobclass/create.rb
- jobclass/createview.rb
- jobclass/my-import.rb
- jobclass/my-migrate.rb
- jobclass/rebuild-drop.rb
- jobclass/rebuild-rename.rb
- lib/bricolage/psqldatasource.rb
トランザクション数チマチマ削減
- テーブルとデータ作成までをまとめる
- VACUUMはトランザクションブロック内で実行できないのでそこで分離
- ANALYZEはVACUUMのあとにやりたいのでやむなく単独トラン
- 最後のRENAME前のダミーテーブルCREATEもif not existsにして1削減
合計 9 txn → 4 txn
> Reduces number of transactions

- lib/bricolage/psqldatasource.rb
With this change, we can see query locations in system catalogs like
pg_stat_activity or stv_inflight.
> Insert location as a block comment

- jobclass/my-import.rb
- jobclass/my-migrate.rb
- test/home/subsys/migrate.job
- test/home/subsys/my-import.job
`my-import`と`migrate`に`no-backup`オプションを追加します。
現在は、ロード時に宛先テーブルを_oldプリフィクスを付けてバックアップする実装になっています。しかし、データ量を減らしたい場合や、テーブル数を減らしたい場合などは、_oldテーブルが作成されないほうが都合が良いです。このオプションを付けると、_oldテーブルを作成せずに、ロードを実行します。
> Add option to skip creating backup table

- lib/bricolage/application.rb
- lib/bricolage/commandlineapplication.rb
- lib/bricolage/jobnetrunner.rb
- lib/bricolage/postgresconnection.rb
pgの同期系メソッドを使うとシグナルがすべてブロックされるので、async_execに変更した。同時に、クエリー実行中にシグナルに割り込まれたらクエリーを明示的にキャンセルするようにした。
なお、SIGTERMを正しく拾うためにはシグナルハンドラのインストールが必要なので、Bricolageアプリケーションの場合のみシグナルハンドラを設定する（条件はいくらか控えめにした）。
> Use asynchronous pg methods

- lib/bricolage/mysqldatasource.rb
- test/home/subsys/my-import.job
my-importジョブクラスでtimezoneの変換をサポートします。
データソース設定ファイルまたはジョブファイルで、`src_zone_offset`および`dst_zone_offset`を定義すると、MySQLでTIMESTAMP型またDATETIME型として定義されているカラムのタイムゾーン（GMTからのオフセット）を変換します。
MySQLのTIMESTAMP型およびDATETIME型はタイムゾーン情報を保持していないため、`src_zone_offset`を基準として変換を行います。デフォルトの`src_zone_offset`は+00:00です。
srcがdstと等しい場合は変換を行いません。
@aamine please review
> Support timezone conversion with my-import

- lib/bricolage/mysqldatasource.rb
MySQLのデータソース定義で、collationというJDBCの接続プロパティを設定出来るようにします。
@aamine
> Enable collation option for JDBC connection property

- jobclass/my-import.rb
- jobclass/my-migrate.rb
既存テーブルを新しいテーブルとトランザクションの中ですりかえるとき、既存テーブルをdropしてしまうと、すでに実行中のトランザクションからテーブルがdropされたことが見えてしまい、"table dropped in concurrent transaction" のエラーになる。
ref: http://stackoverflow.com/questions/20692518/how-can-i-ensure-synchronous-ddl-operations-on-a-table-that-is-being-replaced
このエラーを回避するためには、dropを別トランザクションで実施しなければならない。
> my-migrate, my-import: Do not drop old tables in the RENAME transaction

- lib/bricolage/jobnet.rb
- lib/bricolage/jobnetrunner.rb
bricolage-jobnet で .job ファイル渡されたらジョブ1つだけのジョブネット扱いにします。
[lib/bricolage/jobnetrunner.rb#L40](https://github.com/KOBA789/bricolage/blob/5a9912c563ed48fbc8bc035dc9598c97d907503d/lib/bricolage/jobnetrunner.rb#L40) で `.job` は削らず、`.jobnet` しか削ってないのは、basename 部が同名の job と jobnet があった場合(考えたくないが)にログファイルの名前などを衝突させないためです。
この辺は設計(思想)上の判断が必要だと思うので、適宜指摘をお願いします。
> Treat as jobnet contains the single job if passed *.job file

- lib/bricolage/application.rb
- lib/bricolage/context.rb
- lib/bricolage/filesystem.rb
- lib/bricolage/job.rb
- lib/bricolage/jobnetrunner.rb
- lib/bricolage/logfilepath.rb
- test/test_logfilepath.rb
- bricolage: new option --log-path.
- bricolage, bricolage-jobnet: new option --log-dir.
- bricolage, bricolage-jobnet: new env BRICOLAGE_LOG_PATH.
- bricolage, bricolage-jobnet: new env BRICOLAGE_LOG_DIR.
- new log path format: %{std}
bricolageコマンドにも `--log-path` オプションを付けた。
新しいオプション `--log-dir` を導入した。`--log-dir=PREFIX` は `--log-path=PREFIX/%{std}.log` に等しい。 `%{std}` は `%{jobnet_start_date}/%{jobnet}/%{jobnet_start_time}/%{subsystem}-%{job}` に等しい。
BRICOLAGE_LOG_PATH環境変数は `--log-path` と同じ。
BRICOLAGE_LOG_DIR環境変数は `--log-dir` と同じ。
ref: #52
> Introduce new log file options

- RELEASE.md
- lib/bricolage/version.rb
Want to release 2.24.3 which includes AWS SDK update in `bin/mys3dump` to support ECS task role with my-import job class.
```
gem build bricolage.gemspec 
```
```
gem push bricolage-5.24.3.gem
```
please review
> version 2.24.3

- lib/bricolage/mysqldatasource.rb
Print mys3dump commands err output to stderr output stream of ruby.
Before this fix, both stdout and stderr of mys3dump command is routed to stdout stream of ruby.
> Print mys3dump stderr output to stderr stream

- lib/bricolage/mysqldatasource.rb
There is no need to use `each_with_index` since index value is not used.
> Remove unused idx

- lib/bricolage/mysqldatasource.rb
Write mys3dump command output to log. Which is unintentionally remove with https://github.com/bricolages/bricolage/pull/105 .
@aamine
> [fix] Log mys3dump command output

- lib/bricolage/jobnetrunner.rb
新規コマンドラインオプション2つを追加
- `--disable-queue`: ジョブキューを明示的にオフにする。 `config/bricolage.yml` よりも優先されるので、デフォルトではオンにしておきつつ一部のジョブネットだけオフにできる。
- `--clear-queue`: 永続化されているジョブキューをクリアする。最初からやりなおしたいときに使う。
@bricolages/all おねがいします
> Adds queue handling options

- jobclass/create.rb
- jobclass/createview.rb
- jobclass/load.rb
- jobclass/rebuild-drop.rb
- jobclass/rebuild-rename.rb
- jobclass/sql.rb
job classスクリプト内で `dest-table` を参照するとき、 `params['dest-table']` を使ってしまうとスクリプトのコンパイル時にすべての変数が展開されてしまう。しかしコンパイル時と実行時だと使える変数が異なる（前者のほうがアクセス可能な変数が少ない）ので、.ctファイルに定義されたデフォルト値などが使えなくなってしまう。
この影響で例えば `bricolage create --table-def=XXXX.ct` を実行すると、たとえ.ctファイルに `dest-table` のデフォルト値が設定されていてもgrant対象テーブル名が空になりエラーになってしまっていたのだが、それは意図していない動きなので解決したい。
> fix: Allows $dest_table to use default value of declarations

- bricolage.gemspec
- lib/bricolage/dao/job.rb
- lib/bricolage/dao/jobexecution.rb
- lib/bricolage/dao/jobnet.rb
- lib/bricolage/job.rb
- lib/bricolage/jobnet.rb
- lib/bricolage/jobnetrunner.rb
- lib/bricolage/sqlutils.rb
- lib/bricolage/taskqueue.rb
- schema/Gemfile
- schema/Schemafile
- schema/database.yml
- schema/ridgepole_dryrun.sh
- schema/ridgepole_merge.sh
- test/home/subsys/test_exist.queue
- test/test_taskqueue.rb
bricolageのqueueを実行環境のローカルファイルとして管理する方法とは別に、専用データベースを使って管理する方法を追加します。
一度方針を確認していただくためにDraft PR化しておきます。まだWIPです。
3900866 PostgreSQLにridgepoleで必要なテーブル用意する
6b62a8b TaskQueue用のテストを用意しつつ、DatabaseTaskQueueを追加する
1. testが通るように修正する
2. 生SQLを触っているのをなんとかする
- Job, JobNet, JobExecution, JobExecutionState classをそれぞれ作るはず
3. 実行からの流れに手を加える
- optionの付け方とかデフォルトがDB or Fileなのかとか
設計時に`*.LOCK` のことを忘れていた。`lock`/`unlock`を`job_executions/status`で表現して他の状態を示すものをmessageに書こうか、lock用カラムを追加するか
（今のところは前者で書いているが、後者のほうが良さそうに感じる）
> Add database task queue

- lib/bricolage/jobnetrunner.rb
- lib/bricolage/taskqueue.rb
https://github.com/bricolages/bricolage/pull/114 の内容にバグが残っていましたので修正です
1. ジョブの中にエラーが含まれてfailした `job_executions` が、その後に復帰してもmessageが残る
2. jobnetエラー時に出力するログに用いるオブジェクトのスコープを間違えていた
> Bug fix for #114

- lib/bricolage/application.rb
- lib/bricolage/context.rb
- lib/bricolage/job.rb
- lib/bricolage/jobnetrunner.rb
- test/test_variables.rb
https://github.com/bricolages/bricolage/issues/115 対応です
`-v` オプションで入れる変数を使ってjobnet内jobの`src-table` などを書き換えられるようにします
bricolage内部で数種類存在する変数の種類を一つ増やし、`option_variables` を追加します。
今まで `global_variables` として渡っていた -v オプションの変数指定を `option_variables` に変え、 `@global_variables` はそのままにして、優先順位の上位に追加した変数を加えます。
ローカルでjobnetを実行し、jobnet内にあるjobのsrc-tableで指定している変数書き換えができてることは確認しました
> Change priority of variable from command v option

- .gitignore
- schema/Dockerfile
- schema/Gemfile.lock
開発環境でridgepoleをするために用意していた `/schema` 以下を、本番DBにも適用できるようにするため、Dockerfile（とGemfile.lock）を追加します。
> Add Dockerfile and Gemfile.lock for build docker image to migrate DB

- lib/bricolage/psqldatasource.rb
Unload fails with syntax error when a query has
backslash in it.
Example query with backslash
```
select
replace(column, '\\','\\\\')
from
table
;
```
Generated unload query
```
unload ('select replace(column, \'\\\',\'\\\\\') from table;')
```
Error message
```
ERROR:  syntax error at or near "\"
LINE 1: unload ('select replace(column, \'\\\',\'\\\\\') from table...
```
`replace(column, \'\\\',\'\\\\\')` should be
`replace(column,\'\\\\\',\'\\\\\\\\\')`.
> [fix] Unload fails when a query has backslash

- lib/bricolage/dao/job.rb
- lib/bricolage/dao/jobexecution.rb
- lib/bricolage/dao/jobnet.rb
- lib/bricolage/psqldatasource.rb
- lib/bricolage/taskqueue.rb
DAOのために用意した `DAO::Job` `DAO::JobNet` `DAO::JobExecution` がそれぞれ個別に `PostgresConnection` を開いていました。
できうる限りbricolage DBとのコネクションを同じものを使い回せるように、同一のdatasourceから張るコネクションを一本に共通化するメソッドを追加し、そちらでコネクションを張るようにしました。
DAOからbricolage DBに接続する際はすべてこの `open_shared_connection` を利用するようにします。
> Replace DAO connection to one shared connection from three separated connections

- lib/bricolage/dao/job.rb
- lib/bricolage/dao/jobexecution.rb
- lib/bricolage/dao/jobnet.rb
- lib/bricolage/exception.rb
- lib/bricolage/jobnetrunner.rb
- lib/bricolage/sqlutils.rb
- lib/bricolage/taskqueue.rb
- schema/Schemafile
- test/test_c_streaming_load.rb
- test/test_taskqueue.rb
https://github.com/bricolages/bricolage/pull/122 と https://github.com/bricolages/bricolage/pull/123 を出した後に話し合った結果、bricolageのlockに関して設計変更をすることになりました
- lockはジョブの実行ではなくjobsとjobnetsに対してとることにする
- jobs / jobnets テーブルはカタログだけではなくlock状態管理にも使われるようになる
- jobのロックとjobnetのロックが分かれる
- executor_id というジョブ実行者を区別するIDを用意し、埋まっているとlockということにする
- executor_id は実行環境がECSだったときは task_idを、そうでなければホストネームのどちらかをPIDと組み合わせて作成する
- lockにより防ぎたいのは同一ジョブの重複実行である
- 今までのタイミングでlock/unlockしていたのはjobnetのlock
- ジョブの実行前後でjobのlock/unlockをする
> Replace lock system strategy  to use executor info

- lib/bricolage/dao/job.rb
- lib/bricolage/dao/jobexecution.rb
- lib/bricolage/dao/jobnet.rb
- lib/bricolage/exception.rb
- lib/bricolage/taskqueue.rb
- schema/Schemafile
- test/test_taskqueue.rb
https://github.com/bricolages/bricolage/pull/124 の修正を前提としています
なのでこちらのPRは#124 マージ後にマージします
今までjobと1対1になっていたjob executionを1対nにし、実行のたびに増えるようにします。
また、それにあわせてJobTaskまわりに改修を加えてjob_execution情報を格納できるようにします。
- 4cef9ca JobExecutionのリファクタ
- a76bf73 upsertをやめてcreateを使うようにする（実行のたびにレコードが増えるようになる）
- 5d5307f jobexecutionの指定をsubsystem/job_nameだったのをやめてjob_execution_id指定にする
- 11fac7e JobTaskにjob_executionの情報をもたせるようにする
- DatabaseTaskQueueのときだけ入り、他のときはnilが入る
bricolageが実行するrubyプロセス内での実質的案キューは`@queue`であり、その`@queue` に格納するオブジェクトで`job_execution`の`state`更新や`job`/`jobnets`の`lock`更新を行うようにします。このため、JobTask内部に`job_execution`のidや`job_id`を格納します。
このため `restore_if_exist`で呼ぶ`enqueue_job_executions`内部でJobTaskを`@queue`に詰めるため、`@queue`のサイズが変わるタイミングが既存の`FileTaskQueue`と異なるようになり、テスト内容も変更しました。 …
> Separate job execution by each execution

- lib/bricolage/dao/job.rb
- lib/bricolage/dao/jobexecution.rb
- lib/bricolage/dao/jobnet.rb
- lib/bricolage/taskqueue.rb
- schema/Schemafile
- test/test_taskqueue.rb
#124 を前提として書いていた https://github.com/bricolages/bricolage/pull/126 の内容をmasterにマージするためのPRです
#126 マージ後の `replace_lock_info_to_executor_info` ブランチをcheckout して`git rebase master` しました。テスト、ローカルでの実行ともに問題ないことを確認済みです。
また、コード変更内容を見た限りでは https://github.com/bricolages/bricolage/commit/f27d7cac1d01fb91690fd9ddedb2957b5808903e による変更がそのままきており、approve済みの内容です。
> Merge into master from #126 pr commits

- lib/bricolage/jobnetrunner.rb
- lib/bricolage/taskqueue.rb
- test/home/subsys2/job1.job
- test/home/subsys2/job2.job
- test/home/subsys2/net.jobnet
- test/test_taskqueue.rb
DatabaseTaskQueueを使ったジョブ実行をテストしていたところ、内部でjobnetを呼び出すjobnetの実行がうまくいっていませんでした。エラーにはならず、該当部分を読み飛ばして実行されてしまいます。
`jobnetrunner.rb` で読み込んだ後に作られる `RootJobNet` をそのまま使わず、`JobNetRef` にしてから `JobRef` を読みだそうとしていました。
そうではなく `RootJobNet#sequential_jobs` を使って対象となるjobnetに含まれる全 job一覧を引きだすようにします。
また、変更にあわせて元々おかしかったテストも修正&ケース追加しました。
> Fix execution of jobnet in jobnet for DatabaseTaskQueue

- lib/bricolage/dao/job.rb
- lib/bricolage/dao/jobexecution.rb
- lib/bricolage/dao/jobnet.rb
- lib/bricolage/jobnetrunner.rb
- lib/bricolage/taskqueue.rb
- test/test_taskqueue.rb
DBtaskqueueにおいて、ジョブが失敗したときにDB内部のキューを消す方法がなかったので既存の `--clear-queue` オプションにあわせて機能を追加しました。
また、併せてテスト用に使っていたメソッドを改名&作り直して、テストを複数回実行してもDBに影響が出ないようにDB内データを消す `DatabasetTaskQueue#reset` と各種DAOに`#delete` を追加しました。
> Add clear_queue for database taskqueue

- lib/bricolage/dao/job.rb
- lib/bricolage/dao/jobexecution.rb
- lib/bricolage/dao/jobnet.rb
- lib/bricolage/taskqueue.rb
- test/test_taskqueue.rb
`-l` オプションで jobnet内にあるjobnet（=subnet）のジョブキューがDatabaseTaskQueue版とFileTaskQueue版で一致するかを確認していたところ、一度DB内部に格納したキューを呼び出すときだけRootJobNetのsubsysteで上書きされていました。
`DAO::JobExecution` の読み出しが`jobnets`テーブル側の`subsystem` を読んでいたためです。
`jobs` テーブル側の`subssytem` を読み出す用に修正します。
> Fix subsystem for task of DatabaseTaskQueue

- lib/bricolage/taskqueue.rb
`JobExecution#where` で取得した job_executions はPGを経由して全てStringとして受け取っていました。このため、そのままの値で `Array#sort_by` してしまうと、辞書順ソートとなり `execution_sequence` が10を超えるとソート順がおかしくなります。
ソート時に `execution_sequence` を Integerに変換してからソートするようにします。
> Fix bug of execution_sequence about type from String to Integer

- lib/bricolage/datasource.rb
- lib/bricolage/logger.rb
- lib/bricolage/postgresconnection.rb
- lib/bricolage/psqldatasource.rb
For #137 第一弾
- psqlデータソースに新しいオプションquery_sql_log_levelとupdate_sql_log_levelを追加して、SELECT系とUPDATE系で別のログレベルを使えるようにした（いずれもデフォルト値はsql_log_level）。
- データソースのloggerを変更可能にした。
- Bricolage::Loggerのlevelをnewで指定できるようにした。
これでライブラリとして使っている場合はログに出すSQLをかなりコントロールできるようになる。
> enhancements: Allows PSQLDataSource users to customize the logger

- lib/bricolage/loglocator.rb
ジョブのログファイルをS3にアップロード成功したらローカルファイルは消す。
Docker化してからというもの、謎のECSエラーが低確率で起こるようになっているのだが、ローカルファイルが残っているせいではないか説が挙げられている。原因がわからなすぎるのでとりあえず消して様子を見る。
> tmp?: Removes local log files after S3 uploading is succeeded

- lib/bricolage/context.rb
- lib/bricolage/logger.rb
- lib/bricolage/loglocator.rb
これまでは「ログをstderrに吐いておりstderrが端末ならDEBUGレベル、それ以外はINFO」だったが、この条件だとDocker実行のときにもすべてDEBUGレベルになってしまう。
ちょっとださいが、とりあえず「BRICOLAGE_ENV=developmentのときにDEBUG、それ以外はINFO」にする。
> Use upper log threshold by default

- lib/bricolage/psqldatasource.rb
- test/home/subsys/unified.sql.job
デフォルトで、更新系クエリーはINFOログ、参照系クエリーはDEBUGログを吐くようにする。
> Default log level is INFO for updates, DEBUG for queries

- lib/bricolage/loglocator.rb
ログファイルをS3に上げるとき、printしてからローカルファイルを消す。
S3から手で持ってこないとログが見えない問題のとりあえずの対策。
これはこれで、ジョブネット内のログが全部ごちゃっと出力されてしまってよくない。
> [6.0beta] tmp: Prints a job log after uploading the file

- lib/bricolage/taskqueue.rb
ジョブ管理システムの重複実行ロックと役割がかぶっており、両方行われると不便極まりないので、DBキューについては（一時的に）ロックしないことにする。
> Disables jobnet / job locking

- lib/bricolage/context.rb
development環境ではDEBUGをデフォルトにしてみたが、そもそもbricolageのDEBUGログが出てもあまり意味はなく、それ以下のレベルがないためにログを消す方法もなくなってしまうので、常にINFOをデフォルトにする。
ログレベル変えるコマンドラインオプションも付けるべきだな。
> Default log level is always INFO

- lib/bricolage/context.rb
- lib/bricolage/dao/jobexecution.rb
- lib/bricolage/dao/jobnet.rb
- lib/bricolage/jobnet.rb
- lib/bricolage/jobnetrunner.rb
- lib/bricolage/taskqueue.rb
DBキューで--clear-queueを実行するとき、エンキューしたときとキャンセルしたときでジョブネットの定義が変わっていると、エンキューされているジョブがジョブネットにもう存在しない場合がある。そのようなケースでジョブネットに定義されているジョブだけをキャンセルするとキャンセルしそこなうジョブがあるため、キュー内のジョブをすべて対象としてキャンセルすべき。
いろいろ修正を入れてしまったが一番肝心な変更は ff55f5d である。
> fix: --clear-queue should cancel all queued jobs

- lib/bricolage/job.rb
log_pathが定義されていないとstatus_pathが設定されず、ジョブネット実行でメッセージが失われていた。status_pathは常にtmpdir以下にランダム値で作成するようにする。
> fix: Always define status_path regardless of log_path definition

- bricolage.gemspec
Upgrade pg from 0.18 to 1.2.3.
pg 1.x does not support Redshift (PostgreSQL 8) officially so we have no guarantee, but we cannot stay 0.18 forever, too.
> Upgrade pg to 1.2

- jobclass/rebuild-rename.rb
In alter table rename statement, schema name cannot be specified with new table name.
NG: `alter table hoge.old_name rename to hoge.new_name`
OK: `alter table hoge.old_name rename to new_name`
> [fix] Schema name cannot be specified with alter table rename.

- lib/bricolage/psqldatasource.rb
コネクションプールの実装で、コネクションを閉じそこねる問題がいくつかあったので修正する。
> fix: Pooled connection was not recycled on normal block exit

- lib/bricolage/job.rb
- test/test_variables.rb
For #161 
理由はまったく覚えていないのだが、ジョブパラメーターを展開するときにrest_variablesを入れてないのが原因だった。
> new: Allows to refer job file variables (rest variables) from job parameters

- jobclass/unload.rb
- lib/bricolage/psqldatasource.rb
Parquet is supported since 2019-12-03.
https://aws.amazon.com/about-aws/whats-new/2019/12/announcing-amazon-redshift-data-lake-export/
JSON is supported since 2022-02-16.
https://aws.amazon.com/about-aws/whats-new/2022/02/amazon-redshift-unloading-data-json-files/
> Add Parquet and JSON to unload formats

- lib/bricolage/configloader.rb
Ruby 3.1 (or Psych 4.0) changes `Psych.load` behavior: https://github.com/ruby/psych/releases/tag/v4.0.0 
This commit allows to use aliases in config YAML because:
- Aliases are useful (especially for datasource.yml) and already used in Cookpad, and
- Config files are written by developers themselves.
I manually confirmed to pass tests on my local machine with Ruby 3.0.5 and Ruby 3.1.3, with/without modifications of `config/test/datasource.yml` as follows
```diff
--- a/config/test/datasource.yml
+++ b/config/test/datasource.yml
@@ -1,4 +1,4 @@
-test_db:
+test: &test
type: psql
host: localhost
port: 5432
@@ -7,3 +7,6 @@ test_db:
password: bricolage_test
encoding: utf8
sql_log_level: DEBUG
+
+test_db:
+  <<: *test
```
> Allow to use aliases on config YAMLs

- bricolage.gemspec
In order to use bricolage with Ruby 3.2, we need pg >= 1.3.0: https://github.com/ged/ruby-pg/issues/413
Also, pg 1.4.0 and 1.4.1 fixes issues around keyword argument warnings on Ruby 2.7: https://github.com/ged/ruby-pg/blob/master/History.md#v141-2022-06-24-lars-kanis-larsgreiz-reinsdorfde
It seems there are no reasons to limit pg to '< 1.3', so I relax the current requirements to '>= 1.2.3' and '< 2'.
----
Also, I would appreciate if you could release a new version (6.0.0beta7?) of bricolage in order to use new bricolage by other gems.
> Relax version constraint of pg gem
